name: flutter_app
description: A new Flutter project.

environment:
  sdk: '^3.5.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^12.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  assets:
    - assets/bell.jpg
    - assets/cal-icon.png
    - assets/clock.png
    - assets/activity.png
    - assets/remainder.png
    - assets/bg.jpg
    - assets/alarm.mp3

